# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mateusregasi/Documents/exercicios/sistemas_operacionais/trabalho01

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mateusregasi/Documents/exercicios/sistemas_operacionais/trabalho01

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusregasi/Documents/exercicios/sistemas_operacionais/trabalho01/CMakeFiles /home/mateusregasi/Documents/exercicios/sistemas_operacionais/trabalho01//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusregasi/Documents/exercicios/sistemas_operacionais/trabalho01/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gerenciador_memoria_virtual

# Build rule for target.
gerenciador_memoria_virtual: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gerenciador_memoria_virtual
.PHONY : gerenciador_memoria_virtual

# fast build rule for target.
gerenciador_memoria_virtual/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/build
.PHONY : gerenciador_memoria_virtual/fast

src/HashMap.o: src/HashMap.c.o
.PHONY : src/HashMap.o

# target to build an object file
src/HashMap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/HashMap.c.o
.PHONY : src/HashMap.c.o

src/HashMap.i: src/HashMap.c.i
.PHONY : src/HashMap.i

# target to preprocess a source file
src/HashMap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/HashMap.c.i
.PHONY : src/HashMap.c.i

src/HashMap.s: src/HashMap.c.s
.PHONY : src/HashMap.s

# target to generate assembly for a file
src/HashMap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/HashMap.c.s
.PHONY : src/HashMap.c.s

src/ProcessHashMap.o: src/ProcessHashMap.c.o
.PHONY : src/ProcessHashMap.o

# target to build an object file
src/ProcessHashMap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessHashMap.c.o
.PHONY : src/ProcessHashMap.c.o

src/ProcessHashMap.i: src/ProcessHashMap.c.i
.PHONY : src/ProcessHashMap.i

# target to preprocess a source file
src/ProcessHashMap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessHashMap.c.i
.PHONY : src/ProcessHashMap.c.i

src/ProcessHashMap.s: src/ProcessHashMap.c.s
.PHONY : src/ProcessHashMap.s

# target to generate assembly for a file
src/ProcessHashMap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessHashMap.c.s
.PHONY : src/ProcessHashMap.c.s

src/ProcessQueue.o: src/ProcessQueue.c.o
.PHONY : src/ProcessQueue.o

# target to build an object file
src/ProcessQueue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessQueue.c.o
.PHONY : src/ProcessQueue.c.o

src/ProcessQueue.i: src/ProcessQueue.c.i
.PHONY : src/ProcessQueue.i

# target to preprocess a source file
src/ProcessQueue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessQueue.c.i
.PHONY : src/ProcessQueue.c.i

src/ProcessQueue.s: src/ProcessQueue.c.s
.PHONY : src/ProcessQueue.s

# target to generate assembly for a file
src/ProcessQueue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/ProcessQueue.c.s
.PHONY : src/ProcessQueue.c.s

src/Simulador.o: src/Simulador.c.o
.PHONY : src/Simulador.o

# target to build an object file
src/Simulador.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/Simulador.c.o
.PHONY : src/Simulador.c.o

src/Simulador.i: src/Simulador.c.i
.PHONY : src/Simulador.i

# target to preprocess a source file
src/Simulador.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/Simulador.c.i
.PHONY : src/Simulador.c.i

src/Simulador.s: src/Simulador.c.s
.PHONY : src/Simulador.s

# target to generate assembly for a file
src/Simulador.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/Simulador.c.s
.PHONY : src/Simulador.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main.c.s
.PHONY : src/main.c.s

src/main_menu.o: src/main_menu.c.o
.PHONY : src/main_menu.o

# target to build an object file
src/main_menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main_menu.c.o
.PHONY : src/main_menu.c.o

src/main_menu.i: src/main_menu.c.i
.PHONY : src/main_menu.i

# target to preprocess a source file
src/main_menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main_menu.c.i
.PHONY : src/main_menu.c.i

src/main_menu.s: src/main_menu.c.s
.PHONY : src/main_menu.s

# target to generate assembly for a file
src/main_menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/main_menu.c.s
.PHONY : src/main_menu.c.s

src/n_interpreter.o: src/n_interpreter.c.o
.PHONY : src/n_interpreter.o

# target to build an object file
src/n_interpreter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/n_interpreter.c.o
.PHONY : src/n_interpreter.c.o

src/n_interpreter.i: src/n_interpreter.c.i
.PHONY : src/n_interpreter.i

# target to preprocess a source file
src/n_interpreter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/n_interpreter.c.i
.PHONY : src/n_interpreter.c.i

src/n_interpreter.s: src/n_interpreter.c.s
.PHONY : src/n_interpreter.s

# target to generate assembly for a file
src/n_interpreter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/n_interpreter.c.s
.PHONY : src/n_interpreter.c.s

src/nalloc.o: src/nalloc.c.o
.PHONY : src/nalloc.o

# target to build an object file
src/nalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nalloc.c.o
.PHONY : src/nalloc.c.o

src/nalloc.i: src/nalloc.c.i
.PHONY : src/nalloc.i

# target to preprocess a source file
src/nalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nalloc.c.i
.PHONY : src/nalloc.c.i

src/nalloc.s: src/nalloc.c.s
.PHONY : src/nalloc.s

# target to generate assembly for a file
src/nalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nalloc.c.s
.PHONY : src/nalloc.c.s

src/nnc.o: src/nnc.c.o
.PHONY : src/nnc.o

# target to build an object file
src/nnc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nnc.c.o
.PHONY : src/nnc.c.o

src/nnc.i: src/nnc.c.i
.PHONY : src/nnc.i

# target to preprocess a source file
src/nnc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nnc.c.i
.PHONY : src/nnc.c.i

src/nnc.s: src/nnc.c.s
.PHONY : src/nnc.s

# target to generate assembly for a file
src/nnc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/nnc.c.s
.PHONY : src/nnc.c.s

src/process.o: src/process.c.o
.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/process.c.s
.PHONY : src/process.c.s

src/simulador_page.o: src/simulador_page.c.o
.PHONY : src/simulador_page.o

# target to build an object file
src/simulador_page.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/simulador_page.c.o
.PHONY : src/simulador_page.c.o

src/simulador_page.i: src/simulador_page.c.i
.PHONY : src/simulador_page.i

# target to preprocess a source file
src/simulador_page.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/simulador_page.c.i
.PHONY : src/simulador_page.c.i

src/simulador_page.s: src/simulador_page.c.s
.PHONY : src/simulador_page.s

# target to generate assembly for a file
src/simulador_page.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/simulador_page.c.s
.PHONY : src/simulador_page.c.s

src/web_server.o: src/web_server.c.o
.PHONY : src/web_server.o

# target to build an object file
src/web_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/web_server.c.o
.PHONY : src/web_server.c.o

src/web_server.i: src/web_server.c.i
.PHONY : src/web_server.i

# target to preprocess a source file
src/web_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/web_server.c.i
.PHONY : src/web_server.c.i

src/web_server.s: src/web_server.c.s
.PHONY : src/web_server.s

# target to generate assembly for a file
src/web_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gerenciador_memoria_virtual.dir/build.make CMakeFiles/gerenciador_memoria_virtual.dir/src/web_server.c.s
.PHONY : src/web_server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gerenciador_memoria_virtual"
	@echo "... src/HashMap.o"
	@echo "... src/HashMap.i"
	@echo "... src/HashMap.s"
	@echo "... src/ProcessHashMap.o"
	@echo "... src/ProcessHashMap.i"
	@echo "... src/ProcessHashMap.s"
	@echo "... src/ProcessQueue.o"
	@echo "... src/ProcessQueue.i"
	@echo "... src/ProcessQueue.s"
	@echo "... src/Simulador.o"
	@echo "... src/Simulador.i"
	@echo "... src/Simulador.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_menu.o"
	@echo "... src/main_menu.i"
	@echo "... src/main_menu.s"
	@echo "... src/n_interpreter.o"
	@echo "... src/n_interpreter.i"
	@echo "... src/n_interpreter.s"
	@echo "... src/nalloc.o"
	@echo "... src/nalloc.i"
	@echo "... src/nalloc.s"
	@echo "... src/nnc.o"
	@echo "... src/nnc.i"
	@echo "... src/nnc.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/simulador_page.o"
	@echo "... src/simulador_page.i"
	@echo "... src/simulador_page.s"
	@echo "... src/web_server.o"
	@echo "... src/web_server.i"
	@echo "... src/web_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

